version: 2.1

jobs:
  build_and_clippy:
    docker:
      - image: cimg/rust:1.75.0
    steps:
      - run:
          name: Install required libs
          command: |
            sudo apt-get update
            sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
            gstreamer1.0-libav libgstrtspserver-1.0-dev libges-1.0-dev
      - checkout
      - run:
          name: Build
          command: |
            cargo build
            cargo clippy -- -D warnings

workflows:
  build:
    jobs:
      - build_and_clippy
