FROM ubuntu:24.04 as AndroidBuilder
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y wget unzip openjdk-21-jre-headless
WORKDIR /android_sdk/cmdline-tools/latest
RUN wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip \
    && unzip commandlinetools-linux-11076708_latest.zip \
    && mv cmdline-tools/* .
RUN yes | ./bin/sdkmanager --licenses
RUN ./bin/sdkmanager --install "build-tools;35.0.0" "ndk;25.2.9519653"

FROM cimg/rust:1.75.0
USER root

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    cmake ninja-build openjdk-19-jre-headless xz-utils curl \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /usr/local/gstreamer-1.0-android-universal
RUN curl https://gstreamer.freedesktop.org/data/pkg/android/1.24.5/gstreamer-1.0-android-universal-1.24.5.tar.xz | tar --extract --xz
WORKDIR /home/root
COPY --from=AndroidBuilder --chown=circleci /android_sdk /android_sdk
ENV ANDROID_HOME=/android_sdk
ENV GSTREAMER_1_0_ROOT_ANDROID=/usr/local/gstreamer-1.0-android-universal

USER circleci
RUN rustup target add armv7-linux-androideabi aarch64-linux-android i686-linux-android x86_64-linux-android
ENV PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1
