FROM cimg/rust:1.75.0
USER root
RUN apt-get update \
    && apt-get install -y \
    libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
    gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav libgstrtspserver-1.0-dev libges-1.0-dev \
    && rm -rf /var/lib/apt/lists/* \
    && ldconfig
USER circleci
