name: Test Build

on:
  push:
    paths-ignore:
      - 'android'

jobs:
  create_docker_image:
    name: Create Linux Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            docker_image:
              - '.github/workflows/Dockerfile'
      - name: Build Docker image
        if: ${{ steps.filter.outputs.docker_image == 'true' }}
        run: docker build . --file .github/workflows/linux/Dockerfile --tag ghcr.io/voda/linux:${{ github.run_number }}
      - name: Login to GitHub Container Registry
        if: ${{ steps.filter.outputs.docker_image == 'true' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
      - name: Push Docker image
        if: ${{ steps.filter.outputs.docker_image == 'true' }}
        run: |
          docker push ghcr.io/voda/linux:${{ github.run_number }}
          docker tag ghcr.io/voda/linux:${{ github.run_number }} ghcr.io/voda/linux:latest
          docker push ghcr.io/voda/linux:latest
  build:
    name: Build Linux
    needs: create_docker_image
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/voda/linux:latest"
      credentials:
        username: ${{ github.ref }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -B ../build -S .
      - name: Build
        run: cmake --build ../build
