name: Test Linux Build

on:
  push:
    paths-ignore:
      - 'android/**'

jobs:
  create_docker_image:
    name: Create Linux Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            docker_image:
              - '.github/workflows/linux/Dockerfile'
      - name: Build Docker image
        if: ${{ steps.filter.outputs.docker_image == 'true' }}
        run: docker build . --file .github/workflows/linux/Dockerfile --tag ghcr.io/${{ github.repository }}:linux
      - name: Login to GitHub Container Registry
        if: ${{ steps.filter.outputs.docker_image == 'true' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
      - name: Push Docker image
        if: ${{ steps.filter.outputs.docker_image == 'true' }}
        run: |
          docker push ghcr.io/${{ github.repository }}:linux
  build_linux:
    name: Build Linux
    needs: create_docker_image
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/${{ github.repository }}:linux"
      credentials:
        username: ${{ github.ref }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -B ../build -S .
      - name: Build
        run: cmake --build ../build
