name: Docker Image CI

on:
  push:
    paths:
      - ".github/workflows/docker-image.yml"
      - ".github/workflows/Dockerfile"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file .github/workflows/Dockerfile --tag ghcr.io/${{ github.repository }}:${{ github.run_number }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
      - name: Push the docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.run_number }}
          docker tag ghcr.io/${{ github.repository }}:${{ github.run_number }} ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest
