name: Build

on: [push]

jobs:
  build:
      runs-on: ubuntu-latest
      container:
        image: s2esystems/voda-build-environment:latest
      steps:
      - uses: actions/checkout@v3
      - name: ls
        run: ls
      - name: pwd
        run: pwd
      - name: Configure CMake
        run: cmake -B $GITHUB_WORKSPACE/build -S $GITHUB_WORKSPACE/projects
      - name: Build
        run: cmake --build $GITHUB_WORKSPACE/build
